x = input('write anything:')
print('The data type is', type(x))
print('Does only have space?', x.isspace())
print('Is it a number?', x.isnumeric())
print('Is it alphabetical?', x.isalpha())
print('Is it alphanumerical?', x.isalnum())
print('is it in capital letters?', x.isupper())
print('Is it in lowercase?', x.islower())
print('Is it capitalized?', x.istitle())
